#include "protocol.hpp"
#include <sstream>
namespace sgl::proto {
std::string msg_type_to_string(MsgType t){ switch(t){ case MsgType::Hello:return "Hello"; case MsgType::HelloAck:return "HelloAck"; case MsgType::Ping:return "Ping"; case MsgType::Pong:return "Pong"; case MsgType::ProcessCoarse:return "ProcessCoarse"; case MsgType::RefineRois:return "RefineRois"; case MsgType::JobAccepted:return "JobAccepted"; case MsgType::JobRejected:return "JobRejected"; case MsgType::JobComplete:return "JobComplete"; case MsgType::JobFailed:return "JobFailed"; case MsgType::Status:return "Status"; case MsgType::Shutdown:return "Shutdown"; default:return "Unknown"; } }
MsgType msg_type_from_string(const std::string& s){ if(s=="Hello") return MsgType::Hello; if(s=="HelloAck") return MsgType::HelloAck; if(s=="Ping") return MsgType::Ping; if(s=="Pong") return MsgType::Pong; if(s=="ProcessCoarse") return MsgType::ProcessCoarse; if(s=="RefineRois") return MsgType::RefineRois; if(s=="JobAccepted") return MsgType::JobAccepted; if(s=="JobRejected") return MsgType::JobRejected; if(s=="JobComplete") return MsgType::JobComplete; if(s=="JobFailed") return MsgType::JobFailed; if(s=="Status") return MsgType::Status; if(s=="Shutdown") return MsgType::Shutdown; return MsgType::Unknown; }
std::string encode_header_block(const HeaderMap& h){ std::ostringstream oss; for(auto&kv:h) oss<<kv.first<<"="<<kv.second<<"\n"; oss<<"\n"; return oss.str(); }
bool decode_header_block(const std::string& s, HeaderMap& h){ h.clear(); std::istringstream iss(s); std::string line; while(std::getline(iss,line)){ if(line.empty()) continue; auto p=line.find('='); if(p!=std::string::npos) h[line.substr(0,p)] = line.substr(p+1); } return true; }
std::string encode_rois(const std::vector<RegionOfInterest>& rois){ std::ostringstream oss; for(size_t i=0;i<rois.size();++i){ if(i) oss<<";"; auto&r=rois[i]; oss<<r.x<<","<<r.y<<","<<r.w<<","<<r.h<<","<<r.score; } return oss.str(); }
std::vector<RegionOfInterest> decode_rois(const std::string& s){ std::vector<RegionOfInterest> out; std::istringstream iss(s); std::string item; while(std::getline(iss,item,';')){ if(item.empty()) continue; std::istringstream is(item); std::string tok; std::vector<std::string> p; while(std::getline(is,tok,',')) p.push_back(tok); if(p.size()<5) continue; RegionOfInterest r; r.x=std::stoi(p[0]); r.y=std::stoi(p[1]); r.w=std::stoi(p[2]); r.h=std::stoi(p[3]); r.score=std::stod(p[4]); out.push_back(r);} return out; }
bool get_string(const HeaderMap& h,const std::string& key,std::string& out){ auto it=h.find(key); if(it==h.end()) return false; out=it->second; return true; }
bool get_int(const HeaderMap& h,const std::string& key,int& out){ auto it=h.find(key); if(it==h.end()) return false; out=std::stoi(it->second); return true; }
} // namespace sgl::proto
