# CMake generated Testfile for 
# Source directory: /home/bunta/sgl/sgl_obc_pi_jetson_full
# Build directory: /home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_adcs_power "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/test_adcs_power")
set_tests_properties(test_adcs_power PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;89;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_power_scheduler "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/test_power_scheduler")
set_tests_properties(test_power_scheduler PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;99;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_local_processing "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/test_local_processing")
set_tests_properties(test_local_processing PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;103;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_roi_usefulness "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/test_roi_usefulness")
set_tests_properties(test_roi_usefulness PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;107;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_ring_observation "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/test_ring_observation")
set_tests_properties(test_ring_observation PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;111;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_local_pi_run "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_local_pi_run.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_local_pi_run PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;113;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_scheduler_low_budget "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_scheduler_low_budget.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_scheduler_low_budget PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;118;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_scheduler_propulsion_event "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_scheduler_propulsion_event.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_scheduler_propulsion_event PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;123;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_payload_acquisition "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_payload_acquisition.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_payload_acquisition PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;128;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_events_log "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_events_log.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_events_log PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;133;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_payload_image_modes "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_payload_image_modes.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_payload_image_modes PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;138;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_progressive_outputs "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_progressive_outputs.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_progressive_outputs PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;143;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_alignment_fallback "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_alignment_fallback.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight")
set_tests_properties(test_alignment_fallback PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;148;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_manifest_consistency "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_manifest_consistency.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_manifest_consistency PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;153;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
add_test(test_tcp_mode "bash" "/home/bunta/sgl/sgl_obc_pi_jetson_full/tests/test_tcp_mode.sh" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_pi_flight" "/home/bunta/sgl/sgl_obc_pi_jetson_full/build_wsl/sgl_jetson_service" "/home/bunta/sgl/sgl_obc_pi_jetson_full")
set_tests_properties(test_tcp_mode PROPERTIES  _BACKTRACE_TRIPLES "/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;158;add_test;/home/bunta/sgl/sgl_obc_pi_jetson_full/CMakeLists.txt;0;")
subdirs("sgl_star_tracker_module_build")
subdirs("sgl_comms_module_build")
subdirs("sgl_eps_module_build")
subdirs("sgl_thermal_module_build")
subdirs("sgl_propulsion_module_build")
subdirs("sgl_payload_module_build")
